### ISSUE TITLE
server side support

### ISSUE THREAD

**Issue by IZeeXeS** [MDLC01/better-game-mode-switcher-mc#1]
please

**Comment by MDLC01** [comment]
What do you mean exactly by that? What features would you expect from this mod on the server side?

**Comment by IZeeXeS** [comment]
a permission for players for using F3+N

**Comment by IZeeXeS** [comment]
I know that some other people do it this like telling players that he is operators, or something like that

**Comment by MDLC01** [comment]
Oh I see what you mean. Basically, when allowing a player to use the `gamemode` command, automatically granting them gamemaster permissions so that they can use <kbd>F3</kbd>+<kbd>N</kbd> and the game mode switcher.

This is out of the scope of this mod because there is no way in vanilla to allow people to use specific commands without using the permission system. This means servers do it using a modification in the first place, so this is a bug that has to be fixed on their modification.
