### ISSUE TITLE
F3+F4 looses its memory when activating spectator mode

### ISSUE THREAD

**Issue by Felix14-v2** [MDLC01/better-game-mode-switcher-mc#2]
So you can't toggle gamemode to spectator and creative constantly using F3+F4, quick menu will suggest switching to survival mode for the next time instead of spectator.

**Comment by MDLC01** [comment]
Yes, that is the whole point of this mod. As explained in the [README](https://github.com/MDLC01/better-game-mode-switcher-mc#readme):
> Basically, the game mode switcher will never select Spectator by default. Instead, it selects your last non-Spectator game mode.

- If you want to switch between Spectator and another game mode, use <kbd>F3</kbd>+<kbd>N</kbd>.
- Otherwise, use the game mode switcher (<kbd>F3</kbd>+<kbd>F4</kbd>).

That way, if you are, e.g., making a map, and you need to switch between Creative, Adventure and Spectator, you can switch between the first two using the game mode switcher, and spectate the world using <kbd>F3</kbd>+<kbd>N</kbd>.

**Comment by Felix14-v2** [comment]
Hmm, I was expecting "independent switches" to mean that switching gamemode with F3+N wouldn't just affect the quick menu history, but you have implemented a different behavior. Sorry for misunderstanding.

**Comment by MDLC01** [comment]
You are right. The wording "independant switches" might be a bit confusing. I'm reopenning the issue until I find a better wording.
